### ISSUE TITLE
Add the documentation and extend comments

### ISSUE THREAD

**Issue by KoshakLoL** [KoshakLoL/EternalShitposter#12]
We need to write documentation, so the methods info is accessible to contributors.
And also extend comments, because they are lame.

**Comment by KoshakLoL** [comment]
Closed with V2.0.4.2
Documentation is not needed, since there no one will be using this as an interface. Comments are more than enough.

**Comment by paulo-hst** [comment]
Hello!

I’m learning how to create a bot that quote automatically when a user post a defined message in VK Groups.

It’s possible to show me the documentation?
